name: deploy

on: 
  push: 
    branches: 
      - master

jobs: 
  test-and-deploy: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      # - name: Test
      #   run: |
      #     npm install && npm run test
      - name: Install doctl
        run: |
          cd ~
          wget https://github.com/digitalocean/doctl/releases/download/v1.44.0/doctl-1.44.0-linux-amd64.tar.gz
          tar xf ~/doctl-1.44.0-linux-amd64.tar.gz
          sudo mv ~/doctl /usr/local/bin
      - name: Build container
        run: |
          ./scripts/build.sh
      - name: Push container to DigitalOcean registry
        env: 
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          doctl registry login
          docker push registry.digitalocean.com/streetbot/signaler:build-${{ github.sha	}}
          docker push registry.digitalocean.com/streetbot/signaler:latest
      - name: Set image on pod
        env: 
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          doctl kubernetes cluster kubeconfig save streetbot-test
          kubectl set image --namespace streetbot deployment/signaler app=registry.digitalocean.com/streetbot/signaler:build-${{ github.sha	}}